//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

package net.sdo.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.sdo.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sdo.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ShippingServiceCost }
     * 
     */
    public FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ShippingServiceCost createFindPopularItemsResponseItemArrayItemShippingCostSummaryShippingServiceCost() {
        return new FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ShippingServiceCost();
    }

    /**
     * Create an instance of {@link FindPopularItemsResponse.ItemArray }
     * 
     */
    public FindPopularItemsResponse.ItemArray createFindPopularItemsResponseItemArray() {
        return new FindPopularItemsResponse.ItemArray();
    }

    /**
     * Create an instance of {@link FindPopularItemsResponse.ItemArray.Item.ConvertedCurrentPrice }
     * 
     */
    public FindPopularItemsResponse.ItemArray.Item.ConvertedCurrentPrice createFindPopularItemsResponseItemArrayItemConvertedCurrentPrice() {
        return new FindPopularItemsResponse.ItemArray.Item.ConvertedCurrentPrice();
    }

    /**
     * Create an instance of {@link FindPopularItemsResponse }
     * 
     */
    public FindPopularItemsResponse createFindPopularItemsResponse() {
        return new FindPopularItemsResponse();
    }

    /**
     * Create an instance of {@link FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ListedShippingServiceCost }
     * 
     */
    public FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ListedShippingServiceCost createFindPopularItemsResponseItemArrayItemShippingCostSummaryListedShippingServiceCost() {
        return new FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ListedShippingServiceCost();
    }

    /**
     * Create an instance of {@link FindPopularItemsResponse.ItemArray.Item }
     * 
     */
    public FindPopularItemsResponse.ItemArray.Item createFindPopularItemsResponseItemArrayItem() {
        return new FindPopularItemsResponse.ItemArray.Item();
    }

    /**
     * Create an instance of {@link FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary }
     * 
     */
    public FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary createFindPopularItemsResponseItemArrayItemShippingCostSummary() {
        return new FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary();
    }

}
