//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ebay:apis:eBLBaseComponents", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.sdo.jaxb;
