//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

package net.sdo.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Ack" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Build" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="ItemArray">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Item" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ItemID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="EndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="ViewItemURLForNaturalSearch" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                             &lt;element name="ListingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="GalleryURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                             &lt;element name="PrimaryCategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="PrimaryCategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="BidCount" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="ConvertedCurrentPrice">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                                     &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ListingStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TimeLeft" type="{http://www.w3.org/2001/XMLSchema}duration"/>
 *                             &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ShippingCostSummary">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ShippingServiceCost">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                                               &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="ShippingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ListedShippingServiceCost">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                                               &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="WatchCount" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "timestamp",
    "ack",
    "build",
    "version",
    "itemArray"
})
@XmlRootElement(name = "FindPopularItemsResponse")
public class FindPopularItemsResponse {

    @XmlElement(name = "Timestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlElement(name = "Ack", required = true)
    protected String ack;
    @XmlElement(name = "Build", required = true)
    protected String build;
    @XmlElement(name = "Version")
    protected short version;
    @XmlElement(name = "ItemArray", required = true)
    protected FindPopularItemsResponse.ItemArray itemArray;

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the ack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAck() {
        return ack;
    }

    /**
     * Sets the value of the ack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAck(String value) {
        this.ack = value;
    }

    /**
     * Gets the value of the build property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuild() {
        return build;
    }

    /**
     * Sets the value of the build property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuild(String value) {
        this.build = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public short getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(short value) {
        this.version = value;
    }

    /**
     * Gets the value of the itemArray property.
     * 
     * @return
     *     possible object is
     *     {@link FindPopularItemsResponse.ItemArray }
     *     
     */
    public FindPopularItemsResponse.ItemArray getItemArray() {
        return itemArray;
    }

    /**
     * Sets the value of the itemArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link FindPopularItemsResponse.ItemArray }
     *     
     */
    public void setItemArray(FindPopularItemsResponse.ItemArray value) {
        this.itemArray = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Item" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ItemID" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="EndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="ViewItemURLForNaturalSearch" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                   &lt;element name="ListingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="GalleryURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                   &lt;element name="PrimaryCategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="PrimaryCategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BidCount" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="ConvertedCurrentPrice">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *                           &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ListingStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TimeLeft" type="{http://www.w3.org/2001/XMLSchema}duration"/>
     *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ShippingCostSummary">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ShippingServiceCost">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *                                     &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="ShippingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ListedShippingServiceCost">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *                                     &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="WatchCount" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "item"
    })
    public static class ItemArray {

        @XmlElement(name = "Item")
        protected List<FindPopularItemsResponse.ItemArray.Item> item;

        /**
         * Gets the value of the item property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the item property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FindPopularItemsResponse.ItemArray.Item }
         * 
         * 
         */
        public List<FindPopularItemsResponse.ItemArray.Item> getItem() {
            if (item == null) {
                item = new ArrayList<FindPopularItemsResponse.ItemArray.Item>();
            }
            return this.item;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ItemID" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="EndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="ViewItemURLForNaturalSearch" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *         &lt;element name="ListingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="GalleryURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *         &lt;element name="PrimaryCategoryID" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="PrimaryCategoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="BidCount" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="ConvertedCurrentPrice">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
         *                 &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ListingStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TimeLeft" type="{http://www.w3.org/2001/XMLSchema}duration"/>
         *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ShippingCostSummary">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ShippingServiceCost">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
         *                           &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="ShippingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ListedShippingServiceCost">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
         *                           &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="WatchCount" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "itemID",
            "endTime",
            "viewItemURLForNaturalSearch",
            "listingType",
            "galleryURL",
            "primaryCategoryID",
            "primaryCategoryName",
            "bidCount",
            "convertedCurrentPrice",
            "listingStatus",
            "timeLeft",
            "title",
            "shippingCostSummary",
            "watchCount"
        })
        public static class Item {

            @XmlElement(name = "ItemID")
            protected long itemID;
            @XmlElement(name = "EndTime", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar endTime;
            @XmlElement(name = "ViewItemURLForNaturalSearch", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String viewItemURLForNaturalSearch;
            @XmlElement(name = "ListingType", required = true)
            protected String listingType;
            @XmlElement(name = "GalleryURL", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String galleryURL;
            @XmlElement(name = "PrimaryCategoryID")
            protected int primaryCategoryID;
            @XmlElement(name = "PrimaryCategoryName", required = true)
            protected String primaryCategoryName;
            @XmlElement(name = "BidCount")
            protected short bidCount;
            @XmlElement(name = "ConvertedCurrentPrice", required = true)
            protected FindPopularItemsResponse.ItemArray.Item.ConvertedCurrentPrice convertedCurrentPrice;
            @XmlElement(name = "ListingStatus", required = true)
            protected String listingStatus;
            @XmlElement(name = "TimeLeft", required = true)
            protected Duration timeLeft;
            @XmlElement(name = "Title", required = true)
            protected String title;
            @XmlElement(name = "ShippingCostSummary", required = true)
            protected FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary shippingCostSummary;
            @XmlElement(name = "WatchCount")
            protected short watchCount;

            /**
             * Gets the value of the itemID property.
             * 
             */
            public long getItemID() {
                return itemID;
            }

            /**
             * Sets the value of the itemID property.
             * 
             */
            public void setItemID(long value) {
                this.itemID = value;
            }

            /**
             * Gets the value of the endTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getEndTime() {
                return endTime;
            }

            /**
             * Sets the value of the endTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setEndTime(XMLGregorianCalendar value) {
                this.endTime = value;
            }

            /**
             * Gets the value of the viewItemURLForNaturalSearch property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getViewItemURLForNaturalSearch() {
                return viewItemURLForNaturalSearch;
            }

            /**
             * Sets the value of the viewItemURLForNaturalSearch property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setViewItemURLForNaturalSearch(String value) {
                this.viewItemURLForNaturalSearch = value;
            }

            /**
             * Gets the value of the listingType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getListingType() {
                return listingType;
            }

            /**
             * Sets the value of the listingType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setListingType(String value) {
                this.listingType = value;
            }

            /**
             * Gets the value of the galleryURL property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGalleryURL() {
                return galleryURL;
            }

            /**
             * Sets the value of the galleryURL property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGalleryURL(String value) {
                this.galleryURL = value;
            }

            /**
             * Gets the value of the primaryCategoryID property.
             * 
             */
            public int getPrimaryCategoryID() {
                return primaryCategoryID;
            }

            /**
             * Sets the value of the primaryCategoryID property.
             * 
             */
            public void setPrimaryCategoryID(int value) {
                this.primaryCategoryID = value;
            }

            /**
             * Gets the value of the primaryCategoryName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrimaryCategoryName() {
                return primaryCategoryName;
            }

            /**
             * Sets the value of the primaryCategoryName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrimaryCategoryName(String value) {
                this.primaryCategoryName = value;
            }

            /**
             * Gets the value of the bidCount property.
             * 
             */
            public short getBidCount() {
                return bidCount;
            }

            /**
             * Sets the value of the bidCount property.
             * 
             */
            public void setBidCount(short value) {
                this.bidCount = value;
            }

            /**
             * Gets the value of the convertedCurrentPrice property.
             * 
             * @return
             *     possible object is
             *     {@link FindPopularItemsResponse.ItemArray.Item.ConvertedCurrentPrice }
             *     
             */
            public FindPopularItemsResponse.ItemArray.Item.ConvertedCurrentPrice getConvertedCurrentPrice() {
                return convertedCurrentPrice;
            }

            /**
             * Sets the value of the convertedCurrentPrice property.
             * 
             * @param value
             *     allowed object is
             *     {@link FindPopularItemsResponse.ItemArray.Item.ConvertedCurrentPrice }
             *     
             */
            public void setConvertedCurrentPrice(FindPopularItemsResponse.ItemArray.Item.ConvertedCurrentPrice value) {
                this.convertedCurrentPrice = value;
            }

            /**
             * Gets the value of the listingStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getListingStatus() {
                return listingStatus;
            }

            /**
             * Sets the value of the listingStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setListingStatus(String value) {
                this.listingStatus = value;
            }

            /**
             * Gets the value of the timeLeft property.
             * 
             * @return
             *     possible object is
             *     {@link Duration }
             *     
             */
            public Duration getTimeLeft() {
                return timeLeft;
            }

            /**
             * Sets the value of the timeLeft property.
             * 
             * @param value
             *     allowed object is
             *     {@link Duration }
             *     
             */
            public void setTimeLeft(Duration value) {
                this.timeLeft = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the shippingCostSummary property.
             * 
             * @return
             *     possible object is
             *     {@link FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary }
             *     
             */
            public FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary getShippingCostSummary() {
                return shippingCostSummary;
            }

            /**
             * Sets the value of the shippingCostSummary property.
             * 
             * @param value
             *     allowed object is
             *     {@link FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary }
             *     
             */
            public void setShippingCostSummary(FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary value) {
                this.shippingCostSummary = value;
            }

            /**
             * Gets the value of the watchCount property.
             * 
             */
            public short getWatchCount() {
                return watchCount;
            }

            /**
             * Sets the value of the watchCount property.
             * 
             */
            public void setWatchCount(short value) {
                this.watchCount = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
             *       &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class ConvertedCurrentPrice {

                @XmlValue
                protected float value;
                @XmlAttribute
                protected String currencyID;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public float getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(float value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the currencyID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCurrencyID() {
                    return currencyID;
                }

                /**
                 * Sets the value of the currencyID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCurrencyID(String value) {
                    this.currencyID = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ShippingServiceCost">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
             *                 &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="ShippingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ListedShippingServiceCost">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
             *                 &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "shippingServiceCost",
                "shippingType",
                "listedShippingServiceCost"
            })
            public static class ShippingCostSummary {

                @XmlElement(name = "ShippingServiceCost", required = true)
                protected FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ShippingServiceCost shippingServiceCost;
                @XmlElement(name = "ShippingType", required = true)
                protected String shippingType;
                @XmlElement(name = "ListedShippingServiceCost", required = true)
                protected FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ListedShippingServiceCost listedShippingServiceCost;

                /**
                 * Gets the value of the shippingServiceCost property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ShippingServiceCost }
                 *     
                 */
                public FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ShippingServiceCost getShippingServiceCost() {
                    return shippingServiceCost;
                }

                /**
                 * Sets the value of the shippingServiceCost property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ShippingServiceCost }
                 *     
                 */
                public void setShippingServiceCost(FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ShippingServiceCost value) {
                    this.shippingServiceCost = value;
                }

                /**
                 * Gets the value of the shippingType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getShippingType() {
                    return shippingType;
                }

                /**
                 * Sets the value of the shippingType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setShippingType(String value) {
                    this.shippingType = value;
                }

                /**
                 * Gets the value of the listedShippingServiceCost property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ListedShippingServiceCost }
                 *     
                 */
                public FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ListedShippingServiceCost getListedShippingServiceCost() {
                    return listedShippingServiceCost;
                }

                /**
                 * Sets the value of the listedShippingServiceCost property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ListedShippingServiceCost }
                 *     
                 */
                public void setListedShippingServiceCost(FindPopularItemsResponse.ItemArray.Item.ShippingCostSummary.ListedShippingServiceCost value) {
                    this.listedShippingServiceCost = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
                 *       &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class ListedShippingServiceCost {

                    @XmlValue
                    protected float value;
                    @XmlAttribute
                    protected String currencyID;

                    /**
                     * Gets the value of the value property.
                     * 
                     */
                    public float getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     */
                    public void setValue(float value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the currencyID property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCurrencyID() {
                        return currencyID;
                    }

                    /**
                     * Sets the value of the currencyID property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCurrencyID(String value) {
                        this.currencyID = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
                 *       &lt;attribute name="currencyID" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class ShippingServiceCost {

                    @XmlValue
                    protected float value;
                    @XmlAttribute
                    protected String currencyID;

                    /**
                     * Gets the value of the value property.
                     * 
                     */
                    public float getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     */
                    public void setValue(float value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the currencyID property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCurrencyID() {
                        return currencyID;
                    }

                    /**
                     * Sets the value of the currencyID property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCurrencyID(String value) {
                        this.currencyID = value;
                    }

                }

            }

        }

    }

}
